---
- hosts: web
  tasks:
          - name: printenv
            shell: ls /home/ubuntu/ansible/class2 
            register: out
            until: out is succeeded
            retries: 10
            delay: 2
