---
- name: Change ownership of Tomcat installation
  file:
     path: /usr/share/tomcat/
     owner: tomcat
     group: tomcat
     state: directory
     recurse: yes

- name: Configure Tomcat server
  template:
     src: server.xml
     dest: "{{ tomcat_conf_folder }}"
  notify: restart tomcat

- name: Configure Tomcat users
  template:
     src: tomcat-users.xml
     dest: "{{ tomcat_conf_folder }}"
  notify: restart tomcat

- name: Install Tomcat init script
  copy:
     src: tomcat-initscript.sh
     dest: /etc/init.d/tomcat
     mode: 0755
