---
- name: add group "tomcat"
  group: 
       name: tomcat
       state: present

- name: add user "tomcat"
  user: 
       name: tomcat 
       group: tomcat 
       home: /usr/share/tomcat 
       createhome: no
  become: yes
  become_method: sudo

- name: Extract tomcat archive
  unarchive: 
      src: http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz
      dest: /opt/apache-tomcat-7.0.61
      remote_src: yes
  become: yes

- name: Symlink install directory
  file: 
      src: /opt/apache-tomcat-7.0.61 
      path: "{{ tomcat_symlink_path }}" 
      state: link
  become: yes
