---
# tasks file for tomcat
- name: install tomat
  become: true
  yum:
          name: "{{ tomcat_package }}"
          state: latest
  notify: restart tomcat
- name: copy tomcat conf
  become: true
  copy: 
        src:
        dest:


