---
- name: Start Tomcat
  service:
     name: tomcat
     state: started
     enabled: yes

- name: deploy iptables rules
  template:
     src: iptables-save
     dest: /etc/sysconfig/iptables
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
  notify: restart iptables

- name: wait for tomcat to start
  wait_for: 
     port: "{{ http_port }}"
